name: Deploy to EC2

on:
    push:
        branches:
            - "main"

jobs:
    redeploy:
        name: Deploying everthing to EC2
        runson: ubuntu-latest
        steps:
            - name: SSH into server
            - run: |
                echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
                ssh -i ~/ssh_key ubuntu@13.204.68.219
                cd deploy-app/ && git pull
                pnpm install
                pnpm run build
                pm2 restart http-server
                pm2 restart web-server
                pm2 restart ws-server