name: Deploy to EC2
on: 
    push:
        branches: [ main ]

jobs:
    redeploy:
        name: Deploying everything to EC2
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo (required for actions)
            uses: actions/checkout@v3
          - name: Setup SSH Key
            run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
              chmod 600 ssh_key
          - name: Deploy via SSH
            run: |
                ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.204.68.219 << 'EOF'
                # Load bashrc manually to get access to pnpm/pm2
                source ~/.bashrc || true
                export PATH="$HOME/.npm-global/bin:$HOME/.local/share/pnpm:$PATH"

                cd deploy-app/
                git stash || true
                git pull origin main

                pnpm install
                pnpm run build

                pm2 restart http-server || pm2 start http-server
                pm2 restart web-server || pm2 start web-server
                pm2 restart ws-server || pm2 start ws-server
                EOF