name: Deploy to EC2

on:
    push:
        branches: [ main ]
jobs:
    redeploy:
        name: Deploying everthing to EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo (required for actions)
            - uses: action/checkout@v3

            - name: Setup SSH Key
            run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
                chmod 600 ssh_key